### ISSUE TITLE
filter out non-dataset repositories

### ISSUE THREAD

**Issue by SimonGreenhill** [cldf/cldf-buildbot#1]
Rather than [blacklisting](https://github.com/cldf/cldf-buildbot/blob/master/config.py#L5) non-dataset repositories, can we detect them (e.g. look for a 'cldf' directory?)

**Comment by xrotwang** [comment]
We actually can (although at the price of an additional HTTP call to Github per repos)!
```python
>>> for cf in repo.get_contents('cldf'):
...     print(cf.name)
... 
.gitattributes
cldf-metadata.json
cognates.csv
forms.csv
languages.csv
parameters.csv
requirements.txt
sources.bib
```

This will also solve #5 !

**Comment by xrotwang** [comment]
The (slight) drawback of this approach is that it is somewhat lengthy (longer than the 10secs buildbot allows for reconfiguration) - and also requires more GitHub API requests than are allowed for un-authenticated users. Thus, I'll go for a two-step procedure:

1. Retrieve repository data from GitHub by running a separate script, passing in an access token. Write this info to a JSON file
2. Parse the JSON repos data in `config.py`.

Since we'd presumably call `buildbot reconfig` from a fab task anyway, this task can also call the other script.

**Comment by SimonGreenhill** [comment]
Makes sense. One alternative to think about would be to 'curate' this list e.g. as a plain text file in github.com/lexibank/. More work I guess, but would allow us to decide what goes in and when (i.e. we have some datasets that are in progress that don't need to be watched yet), and means the organisation is irrelevant (i.e. we can include third party cldfs outside lexibank and cldf-datasets).

(I'm not arguing strongly for this, just proposing)
