### ISSUE TITLE
Accessing catalogs from the workers

### ISSUE THREAD

**Issue by SimonGreenhill** [cldf/cldf-buildbot#3]
It seems that the simplest way to access catalogs (like Glottolog) from shell commands run on the workers would be as follows:

    run all workers on the same machine
    have clones of the catalogs on this machine
    pass the location of the clones to the workers via env variables.

Note: This would require cldfbench to read these env variables.

There could be an appconfig fab task to update the catalogs.

**Comment by xrotwang** [comment]
Hm. There's a bit of a complication with the "one global catalog" setup. Checking out a specific version per build does not work, because the checkout command creates `.git/index.lock`, which makes subsequent checkout commands fail.

While this is a bit of a pain, I think the main use case of `cldf-buildbot` is having up-to-date, valid builds of all datasets, thus, we can probably live with having a semi-fixed version of the catalogs on the build server. Updating the catalog versions would then be something that happens "out-of-band", e.g. via a fab task.
